app:
  name: clortho

jwt:
  header: Authorization
  expires_in: 300 # 5 minutes
  mobile_expires_in: 600 # 60 minutes
  secret: queenvictoria
  cookie: AUTH-TOKEN
server:
 port: 9125

spring:
  profiles:
    active: dev

---
spring:
  profiles: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/api_auth
    username: authus3r
    password: authus3r
    driverClassName: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
v